// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBljrX2JZiMD-Y6e5PxaFGDjDG9vhhRkbI',
    appId: '1:279248715694:web:7a0db1f591281ad943923f',
    messagingSenderId: '279248715694',
    projectId: 'pingmyride-v1',
    authDomain: 'pingmyride-v1.firebaseapp.com',
    storageBucket: 'pingmyride-v1.firebasestorage.app',
    measurementId: 'G-PMJ6VCDF89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iZiCSXo7TEvu17-tKS7u4UedZ6hjjHk',
    appId: '1:279248715694:android:a1f83113bafffc3c43923f',
    messagingSenderId: '279248715694',
    projectId: 'pingmyride-v1',
    storageBucket: 'pingmyride-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB25lPw08dcgGTAVKaPWEJq-dARKZJeIco',
    appId: '1:279248715694:ios:4b65edb8166a01d243923f',
    messagingSenderId: '279248715694',
    projectId: 'pingmyride-v1',
    storageBucket: 'pingmyride-v1.firebasestorage.app',
    iosBundleId: 'com.sirius.pingmyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB25lPw08dcgGTAVKaPWEJq-dARKZJeIco',
    appId: '1:279248715694:ios:4b65edb8166a01d243923f',
    messagingSenderId: '279248715694',
    projectId: 'pingmyride-v1',
    storageBucket: 'pingmyride-v1.firebasestorage.app',
    iosBundleId: 'com.sirius.pingmyride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBljrX2JZiMD-Y6e5PxaFGDjDG9vhhRkbI',
    appId: '1:279248715694:web:22f8f895bd2921be43923f',
    messagingSenderId: '279248715694',
    projectId: 'pingmyride-v1',
    authDomain: 'pingmyride-v1.firebaseapp.com',
    storageBucket: 'pingmyride-v1.firebasestorage.app',
    measurementId: 'G-HS8WM5KK8B',
  );
}
